#!/usr/bin/env python3
"""Generate the static StreamKind tables for the C++ wire stack.

Runs on the HOST at `make gen` time, where full libprotobuf is available, and
reads the (visio_proto_type) / (visio_mcap_schema_name) EnumValueOptions off
visio_schema.wire.v1.StreamKind. Emits header-only tables that the embeddable
(nanopb) C++ build links directly — the device never performs descriptor
reflection (which nanopb cannot do). The proto remains the single source of truth.

Two outputs (both under <out_dir>/visio_schema/wire/):
  stream_map.gen.hpp      — StreamKind -> {name, proto_type, mcap_schema_name}.
                            Small; always linked.
  stream_schemas.gen.hpp  — StreamKind -> serialized FileDescriptorSet bytes,
                            the schema an on-device MCAP writer registers. Larger
                            (~tens of KB); kept separate so non-recording firmware
                            need not link it.

Usage: gen_stream_map.py <out_dir>
"""
from __future__ import annotations

import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO / "python"))

from visio_schema.wire.streams import file_descriptor_set  # noqa: E402
from visio_schema.wire.v1 import header_pb2 as hdr  # noqa: E402

_MAP_HEADER = """// Generated by scripts/gen_stream_map.py from
// visio_schema.wire.v1.StreamKind annotations — DO NOT EDIT.
//
// Static StreamKind -> payload-type table, replacing runtime descriptor
// reflection (unavailable under nanopb). The proto is the source of truth.
#pragma once

#include <cstdint>
#include <string_view>

namespace visio_schema::wire {{

struct StreamMapEntry {{
  std::int32_t     kind;
  std::string_view name;              // e.g. "STREAM_IMU_RAW"
  std::string_view proto_type;        // e.g. "visio_schema.sensor.v1.ImuRaw"
  std::string_view mcap_schema_name;  // usually == proto_type
}};

inline constexpr StreamMapEntry kStreamMap[] = {{
{rows}
}};

// DeviceClass value -> enum name (e.g. 1 -> "DEVICE_GRIPPER_LEFT"). Used by the
// MCAP endpoint to synthesize topics matching the Python side.
struct DeviceNameEntry {{
  std::int32_t     value;
  std::string_view name;
}};

inline constexpr DeviceNameEntry kDeviceNames[] = {{
{devices}
}};

}}  // namespace visio_schema::wire
"""

_SCHEMAS_HEADER = """// Generated by scripts/gen_stream_map.py from
// visio_schema.wire.v1.StreamKind annotations — DO NOT EDIT.
//
// Per-StreamKind serialized google.protobuf.FileDescriptorSet bytes (payload
// type + transitive deps). An on-device MCAP writer registers these as the
// channel's protobuf Schema, so the device needs no descriptor pool. Built
// host-side where full libprotobuf exists; the embedded build only reads bytes.
//
// Kept out of stream_map.gen.hpp because these blobs are ~tens of KB total and
// only the MCAP-recording path needs them.
#pragma once

#include <cstddef>
#include <cstdint>
#include <string_view>

namespace visio_schema::wire {{

namespace detail {{
{arrays}
}}  // namespace detail

// Serialized FileDescriptorSet for `kind`'s payload, or an empty view if the
// StreamKind is unannotated (service dual-payload streams, CUSTOM, UNKNOWN).
inline std::string_view FileDescriptorSetFor(std::int32_t kind) noexcept {{
  switch (kind) {{
{cases}
    default: return {{}};
  }}
}}

}}  // namespace visio_schema::wire
"""


def _annotated_streams() -> list:
    out = []
    for v in hdr.StreamKind.DESCRIPTOR.values:
        proto_type = v.GetOptions().Extensions[hdr.visio_proto_type]
        if proto_type:
            out.append((v, proto_type))
    return out


def _write_stream_map(out_dir: Path) -> int:
    rows = []
    for v, proto_type in _annotated_streams():
        mcap_name = v.GetOptions().Extensions[hdr.visio_mcap_schema_name] or proto_type
        rows.append(f'    {{{v.number}, "{v.name}", "{proto_type}", "{mcap_name}"}},')
    devices = [
        f'    {{{v.number}, "{v.name}"}},' for v in hdr.DeviceClass.DESCRIPTOR.values
    ]
    (out_dir / "stream_map.gen.hpp").write_text(
        _MAP_HEADER.format(rows="\n".join(rows), devices="\n".join(devices))
    )
    return len(rows)


def _byte_array(name: str, data: bytes) -> str:
    body = ", ".join(str(b) for b in data)
    return (
        f"inline constexpr unsigned char {name}[] = {{{body}}};"
        if data
        else f"inline constexpr unsigned char {name}[] = {{0}};  // unused"
    )


def _write_stream_schemas(out_dir: Path) -> int:
    arrays, cases = [], []
    for v, proto_type in _annotated_streams():
        arr = f"kFds_{v.name}"
        data = file_descriptor_set(proto_type)
        arrays.append(_byte_array(arr, data))
        cases.append(
            f"    case {v.number}: return {{reinterpret_cast<const char*>(detail::{arr}), "
            f"sizeof(detail::{arr})}};"
        )
    text = _SCHEMAS_HEADER.format(arrays="\n".join(arrays), cases="\n".join(cases))
    (out_dir / "stream_schemas.gen.hpp").write_text(text)
    return len(cases)


def main() -> int:
    out_dir = Path(sys.argv[1]) / "visio_schema" / "wire"
    out_dir.mkdir(parents=True, exist_ok=True)
    n_map = _write_stream_map(out_dir)
    n_schemas = _write_stream_schemas(out_dir)
    print(
        f"wrote {out_dir}/stream_map.gen.hpp ({n_map} streams) + "
        f"stream_schemas.gen.hpp ({n_schemas} descriptor sets)",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
