#!/usr/bin/env python3
"""Generate the embedded schema-blob table for the C++ (nanopb) wire stack.

Runs on the HOST at `make gen` time, where full libprotobuf is available. The
dynamic wire model carries no StreamKind enum: a stream's schema is identified
by its fully-qualified protobuf type name and shipped inline as a serialized
``google.protobuf.FileDescriptorSet`` (``Channel.schema``). On-device the nanopb
build cannot do descriptor reflection, so we precompute those bytes here and emit
a header the embedded build links directly.

Output (under <out_dir>/visio_schema/wire/):
  schema_blobs.gen.hpp  — proto FQN -> serialized FileDescriptorSet bytes, plus a
                          FileDescriptorSetFor(std::string_view) lookup. An
                          on-device MCAP writer / DeviceInfo announce registers
                          these as the channel's protobuf Schema, so the device
                          self-describes with no descriptor pool. ~tens of KB;
                          only the recording / announce path links it.

The set of types is sourced from visio_schema.wire.schema._PAYLOAD_MODULES (the
single list of payload modules), so adding a payload type there is the only edit
needed. The proto remains the source of truth.

Usage: gen_schema_blobs.py <out_dir>
"""
from __future__ import annotations

import sys
from importlib import import_module
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO / "python"))

from visio_schema.wire import schema  # noqa: E402

_HEADER = """// Generated by scripts/gen_schema_blobs.py from
// visio_schema.wire.schema._PAYLOAD_MODULES — DO NOT EDIT.
//
// Per-payload-type serialized google.protobuf.FileDescriptorSet bytes (the type
// plus its transitive deps). An on-device MCAP writer registers these as the
// channel's protobuf Schema, and the DeviceInfo announce ships them inline, so
// the device needs no descriptor pool (nanopb cannot reflect). Built host-side
// where full libprotobuf exists; the embedded build only reads bytes.
//
// Keyed by the payload's fully-qualified protobuf type name — the same string a
// Channel carries in schema_name.
#pragma once

#include <cstddef>
#include <string_view>

namespace visio_schema::wire {{

namespace detail {{
{arrays}
}}  // namespace detail

// Serialized FileDescriptorSet for `proto_type`, or an empty view if the type is
// not a known payload (caller declares a Channel with empty schema, leaving the
// MCAP Schema record undescribed).
inline std::string_view FileDescriptorSetFor(std::string_view proto_type) noexcept {{
{cases}
  return {{}};
}}

}}  // namespace visio_schema::wire
"""


def _payload_type_names() -> list[str]:
    """Every top-level message FQN across the canonical payload modules."""
    names: list[str] = []
    for mod_name in schema._PAYLOAD_MODULES:
        mod = import_module(mod_name)
        for desc in mod.DESCRIPTOR.message_types_by_name.values():
            names.append(desc.full_name)
    return names


def _ident(fqn: str) -> str:
    return "kFds_" + fqn.replace(".", "_")


def _byte_array(name: str, data: bytes) -> str:
    body = ", ".join(str(b) for b in data)
    return f"inline constexpr unsigned char {name}[] = {{{body}}};"


def main() -> int:
    out_dir = Path(sys.argv[1]) / "visio_schema" / "wire"
    out_dir.mkdir(parents=True, exist_ok=True)

    arrays, cases = [], []
    for fqn in _payload_type_names():
        data = schema.file_descriptor_set(fqn)
        if not data:
            # A registered payload type with an empty FileDescriptorSet means a
            # broken descriptor pool — fail rather than silently omit its schema
            # (which would leave the on-device MCAP channel undescribed).
            raise RuntimeError(f"empty FileDescriptorSet for {fqn}; run `make gen`")
        arr = _ident(fqn)
        arrays.append(_byte_array(arr, data))
        cases.append(
            f'  if (proto_type == "{fqn}") '
            f"return {{reinterpret_cast<const char*>(detail::{arr}), "
            f"sizeof(detail::{arr})}};"
        )

    (out_dir / "schema_blobs.gen.hpp").write_text(
        _HEADER.format(arrays="\n".join(arrays), cases="\n".join(cases))
    )
    print(
        f"wrote {out_dir}/schema_blobs.gen.hpp ({len(cases)} descriptor sets)",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
