#!/usr/bin/env python3
"""Generate tests/golden/diag_wire_vectors.txt — the diag REQUEST encoding.

`wire/diag` has no cross-language corpus, and `diag_vectors.txt` is not one for
it: that file is generated from `mcap/crypto.py` and pins the VDLG/VDLW log
CONTAINERS, a different layer. So the TypeScript port had nothing to replay,
and a differential run against this reference was the only evidence it agreed.
This makes that evidence permanent.

It pins the request half only, deliberately. That half is a pure codec — one
call, one byte string — which the existing `key=lowercase_hexbytes` grammar
already expresses and every loader in the tree already reads. The REPLY half is
a state machine whose recv pattern the drivers are free to differ on (the same
reason ota_vectors.txt refuses to pin it, so an async driver stays writable);
its behaviour is pinned by each language's own suite instead.

  <case>.msg   the raw DiagRequest bytes the call must produce
"""
from __future__ import annotations

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "python"))

from visio_schema.wire import diag  # noqa: E402

SESSION = 0x51D0

#: Every shape the encoder can produce: each oneof arm, addressed and not, and
#: a read with the defaults that must still encode (offset 0 / len 0 read to
#: the end, and are NOT the same as an absent read).
CASES: dict[str, bytes] = {
    "list": diag.list_message(session_id=SESSION),
    "list_addressed": diag.list_message(session_id=SESSION, target_device="GILABS-A"),
    "abort": diag.abort_message(session_id=SESSION),
    "abort_addressed": diag.abort_message(session_id=SESSION, target_device="GILABS-A"),
    "read": diag.read_message("a.vdlg", 4096, 1024, session_id=SESSION),
    "read_to_end": diag.read_message("b.vdlg", session_id=SESSION),
    "read_addressed": diag.read_message(
        "c.vdlg", 1, 2, session_id=SESSION, target_device="GILABS-B"),
}

HEADER = f"""\
# diag_wire_vectors.txt - the diag REQUEST encoding, shared by every language.
#
# Generated by scripts/gen_diag_wire_vectors.py from the Python reference in
# visio_schema/wire/diag.py. It pins the implementations to each OTHER;
# whether the behaviour is RIGHT is each language's own diag suite.
#
# NOT to be confused with diag_vectors.txt, which is generated from
# mcap/crypto.py and pins the VDLG/VDLW log CONTAINERS - a different layer.
#
# Only the REQUEST half is pinned. It is a pure codec (one call, one byte
# string). The reply half is a state machine, and pinning its recv pattern
# would make an async driver unwritable - the same reason ota_vectors.txt
# refuses to; each language's suite covers that instead.
#
# Every request carries session_id={SESSION:#x}.
#
# Grammar:
#   <case>.msg   the raw DiagRequest bytes the call must produce
"""


def main() -> None:
    out = pathlib.Path(__file__).resolve().parents[1] / "tests/golden/diag_wire_vectors.txt"
    lines = [HEADER]
    for name, msg in CASES.items():
        lines.append(f"{name}.msg={msg.hex()}")
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} ({len(CASES)} cases)")


if __name__ == "__main__":
    main()
