#!/usr/bin/env python3
"""Generate tests/golden/slerp_vectors.txt — the orientation-blend kernel.

`reader.interp.slerp_xyzw` (Python) and `reader/time_history.hpp` `SlerpXyzw`
(C++) are two implementations of one formula, used for one purpose: "what was
this IMU's orientation at that camera exposure". A drift between them does not
fail loudly. It moves a vision residual by a fraction of a degree, which the
yaw filter downstream then treats as real drift. So both suites replay the
bytes below and assert THEIR kernel reproduces them.

Each case is 13 little-endian IEEE-754 doubles, so both languages start from the
identical bits:

  <case>   q0[x,y,z,w]  q1[x,y,z,w]  w  out[x,y,z,w]

The cases cover every branch the kernel has: the plain arc, the short-arc sign
flip (q1 and -q1 are one rotation), the near-parallel nlerp fallback, both
endpoints, and extrapolation past `hi` (the kernel does not clamp `w`; whether a
caller may extrapolate is the caller's decision, not the kernel's). The rest are
seeded random rotation pairs.
"""
from __future__ import annotations

import pathlib
import struct
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "python"))

from visio_schema.reader.interp import slerp_xyzw

OUT = (
    pathlib.Path(__file__).resolve().parents[1] / "tests" / "golden" / "slerp_vectors.txt"
)


def _rot(axis, deg) -> np.ndarray:
    a = np.asarray(axis, float)
    a = a / np.linalg.norm(a)
    h = np.deg2rad(deg) / 2
    return np.concatenate([a * np.sin(h), [np.cos(h)]])


def _cases() -> list[tuple[str, np.ndarray, np.ndarray, float]]:
    z = (0, 0, 1)
    cases = [
        ("arc_mid", _rot(z, 0), _rot(z, 90), 0.5),
        ("arc_quarter", _rot((1, 2, 3), 10), _rot((1, 2, 3), 130), 0.25),
        ("endpoint_lo", _rot((0, 1, 0), 20), _rot((1, 0, 0), 70), 0.0),
        ("endpoint_hi", _rot((0, 1, 0), 20), _rot((1, 0, 0), 70), 1.0),
        # q1 given as its own negation: must take the short arc, not a full turn.
        ("short_arc_flip", _rot(z, 10), -_rot(z, 50), 0.5),
        # 0.5 deg apart: dot > 0.9995, so the nlerp branch.
        ("near_parallel", _rot((1, 1, 0), 30.0), _rot((1, 1, 0), 30.5), 0.3),
        ("extrapolate", _rot(z, 0), _rot(z, 20), 1.5),
    ]
    rng = np.random.default_rng(20260924)
    for k in range(24):
        q0 = rng.normal(size=4)
        q1 = rng.normal(size=4)
        cases.append((f"rand{k:02d}", q0 / np.linalg.norm(q0), q1 / np.linalg.norm(q1),
                      float(rng.uniform(0.0, 1.0))))
    return cases


def main() -> None:
    lines = [
        "# Cross-language golden vectors for the orientation SLERP kernel",
        "# (one `key=hexbytes` per line). Generated by scripts/gen_slerp_vectors.py",
        "# from python/visio_schema/reader/interp.py `slerp_xyzw`. Each value is 13",
        "# little-endian doubles: q0[xyzw] q1[xyzw] w out[xyzw].",
        "# Both python/tests/reader/test_slerp_vectors.py and",
        (
            "# cpp/tests/test_time_history.cc replay these and assert their kernel "
            "matches."
        ),
        "",
    ]
    for name, q0, q1, w in _cases():
        out = slerp_xyzw(q0, q1, w)
        blob = struct.pack("<13d", *q0, *q1, w, *out)
        lines.append(f"{name}={blob.hex()}")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(lines) - 7} cases)")


if __name__ == "__main__":
    main()
