#!/usr/bin/env python3
"""Generate tests/golden/recordings_wire_vectors.txt — the recordings-pull codec.

Pins what every language must agree on byte for byte: the three commands a
host builds (ListRecordings in all its shapes, OpenRecordingFile,
DeleteRecording) and the CommandResult payloads it must decode (an open, a
session's files, a page with a cursor, a refusal). The byte path after an open
is a bare TCP stream with no framing, so there is nothing to pin there; each
language's own suite covers the pull behaviour.

  <case>.cmd      raw Command bytes the builder must produce
  <case>.result   raw CommandResult bytes the decoder must read
"""
from __future__ import annotations

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "python"))

from visio_schema.v1.control import command_result_pb2 as cr
from visio_schema.wire import recordings as rec

SESSION = "session_00042-1789017895"
CURSOR = "v1:1789017895000000:session_00042-1789017895"
MTIME = 1789017895123456789

COMMANDS: dict[str, bytes] = {
    "list": rec.list_recordings_command().SerializeToString(),
    "list_page": rec.list_recordings_command(limit=20, cursor=CURSOR).SerializeToString(),
    "list_session": rec.list_recordings_command(
        session_name=SESSION, target_device="GILABS-A").SerializeToString(),
    "open": rec.open_recording_file_command(SESSION, "ego_0003.mcap").SerializeToString(),
    "open_resume": rec.open_recording_file_command(
        SESSION, "ego_0003.mcap", offset=100663296, expect_size=281018368,
        expect_mtime_ns=MTIME, target_device="GILABS-A").SerializeToString(),
    "delete": rec.delete_recording_command(SESSION, target_device="GILABS-A").SerializeToString(),
}


def results() -> dict[str, bytes]:
    opened = cr.CommandResult(command_id=7, ok=True)
    opened.file_open.CopyFrom(cr.RecordingFileOpen(
        port=50002, offset=100663296, length=180355072, file_size=281018368, mtime_ns=MTIME))

    files = cr.CommandResult(command_id=8, ok=True)
    entry = files.recordings.recordings.add(
        name=SESSION, size_bytes=269484544, started_at_us=1789017895000000, duration_s=12.5,
        active=True, file_count=3)
    entry.files.add(name="ego_0000.mcap", size=268435456, mtime_ns=MTIME, complete=True)
    entry.files.add(name="ego_0001.mcap", size=1048576, mtime_ns=MTIME + 1, writing=True)
    entry.files.add(name="session.json", size=512, mtime_ns=MTIME + 2, writing=True,
                    complete=True)

    page = cr.CommandResult(command_id=9, ok=True)
    page.recordings.recordings.add(name=SESSION, size_bytes=4096, file_count=2)
    page.recordings.recordings.add(name="session_00041-1789010000", size_bytes=8192,
                                   file_count=3, damaged=True)
    page.recordings.next_cursor = CURSOR
    page.recordings.read_while_recording = True

    refused = cr.CommandResult(command_id=10, ok=False, error_code="writing",
                               error_message="ego_0001.mcap is being recorded")
    return {
        "result_open": opened.SerializeToString(),
        "result_session_files": files.SerializeToString(),
        "result_page": page.SerializeToString(),
        "result_refused": refused.SerializeToString(),
    }


HEADER = """\
# recordings_wire_vectors.txt - the recordings-pull codec, shared by every language.
#
# Generated by scripts/gen_recordings_wire_vectors.py from the Python reference in
# visio_schema/wire/recordings.py. It pins the implementations to each OTHER;
# whether a pull BEHAVES right is each language's own suite.
#
# After OpenRecordingFile the bytes travel on a bare TCP stream with no framing,
# so only the commands and their results are pinned here.
#
# Grammar:
#   <case>.cmd      raw Command bytes the builder must produce
#   <case>.result   raw CommandResult bytes the decoder must read
"""


def main() -> None:
    out = pathlib.Path(__file__).resolve().parents[1] / "tests/golden/recordings_wire_vectors.txt"
    lines = [HEADER]
    for name, raw in COMMANDS.items():
        lines.append(f"{name}.cmd={raw.hex()}")
    for name, raw in results().items():
        lines.append(f"{name}.result={raw.hex()}")
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} ({len(COMMANDS)} commands, {len(results())} results)")


if __name__ == "__main__":
    main()
